### ISSUE TITLE
The Font Awesome CSS is not available within the head of the website

### ISSUE THREAD

**Issue by Zorono** [lleblanc42/bootstrap-FileUpload#25]
Hello dude, so i am Trying to load the script with fontawesomev5-pro but it results in ```The Font Awesome CSS is not available within the head of the website and is a required unless the option showThumb is set to false.``` after enabling the debug-mode(on disabling it, it looks like that the script isn't responding as it doesn't show any kind of elements...) but when i try to use that one which is used on the demo `https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css` it works as well... please some help

**Comment by lleblanc42** [comment]
Hello, I'm not sure I follow. The error message is because font-awesome is a dependency and it requires it to create set thumbnails for uploads that are not images.

> https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css it works as well... please some help

It should work with the example as long as the cdn is still available. You could always download the font awesome files and use that instead of a cdn.

**Comment by Zorono** [comment]
I have completed some changes which solve this problem... #27

**Comment by lleblanc42** [comment]
Thank you, I'm going to use some of it in the upcoming release which I'm hoping to finish up tonight or sometime this week. Thank you for your contributions!

**Comment by lleblanc42** [comment]
I've added these fixes to the latest release, closing.
